Repository bio-routing/bio-rd, pull requests merged in 2022-09, with the labels that each got.

#373 Remove redundant bio_bgp_up metric
  metrics/bgp/adapter/prom/bgp_prom_adapter.go
  protocols/bgp/metrics/bgp_peer_metrics.go
  protocols/bgp/server/metrics_service.go
  protocols/bgp/server/metrics_service_test.go
Labels: type:clean-up

#374 Clean up naming for Prefix.pfxlen (to Prefix.len)
  net/api/net.pb.go
  net/api/net.proto
  net/prefix.go
  net/prefix_cache_test.go
  net/prefix_test.go
  protocols/bgp/packet/nlri.go
  protocols/bgp/server/update_sender.go
  route/route.go
  routingtable/filter/prefix_matcher.go
  routingtable/table.go
  routingtable/trie.go
Labels: type:clean-up

#375 RIS: Catch nil pointer in cli and expose EOR
  cmd/riscli/observe_rib.go
Labels: type:bug-fix

#376 BMP: Cover router ready check with tests
  protocols/bgp/server/bmp_router_test.go
Labels: type:tests

#379 BMP: Allow ignoring BGP sessions based on peer ASN
  cmd/ris/config/config.go
  cmd/ris/main.go
  protocols/bgp/server/bmp_router.go
  protocols/bgp/server/bmp_server.go
  protocols/bgp/server/bmp_server_test.go
Labels: type:feature

#381 Rename some remaining occurances of peerAttr(s)
  protocols/bgp/server/fsm_address_family.go
  routingtable/adjRIBOut/adj_rib_out_test.go
Labels: type:clean-up

#382 Reflect Golang net.IP changes
  net/ip.go
  net/ip_test.go
Labels: type:bug-fix

#380 BMP: Implement serialization of BMP messages
  protocols/bmp/packet/initiation_message.go
  protocols/bmp/packet/initiation_message_test.go
  protocols/bmp/packet/peer_down.go
  protocols/bmp/packet/peer_down_test.go
  protocols/bmp/packet/peer_up.go
  protocols/bmp/packet/peer_up_test.go
  protocols/bmp/packet/route_monitoring.go
  protocols/bmp/packet/route_monitoring_test.go
Labels: type:feature

#383 Allow configuring if pre-/policy UPDATEs should be ignored
  cmd/ris/main.go
  protocols/bgp/server/bmp_router.go
  protocols/bgp/server/bmp_server.go
  protocols/bgp/server/bmp_server_test.go
Labels: type:bug-fix, type:improvement

#384 Add IP.To16BytesArray() method
  net/ip.go
  net/ip_test.go
Labels: type:feature

#385 Rename BMP Server to BMP receiver in preparation for BMP Monitoring Station support
  cmd/ris/main.go
  cmd/ris/risserver/server.go
  examples/bmp/main_bmp.go
  metrics/bmp/adapter/prom/bmp_prom_adapter.go
  protocols/bgp/server/bmp_metrics_service.go
  protocols/bgp/server/bmp_receiver.go
  protocols/bgp/server/bmp_receiver_test.go
Labels: type:feature-prep

#386 bnet.IP.String() should be called by value
  net/ip.go
Labels: type:clean-up
