Repository bio-routing/bio-rd, pull requests merged in 2023-01, with the labels that each got.

#405 Index VRFs by name instead of RD
  cmd/bio-rd/main.go
  cmd/ris-mirror/rismirror/router.go
  protocols/bgp/server/bmp_router.go
  routingtable/vrf/vrf.go
  routingtable/vrf/vrf_registry.go
  routingtable/vrf/vrf_test.go
Labels: type:improvement, type:clean-up

#407 BGP: Make TCP listener VRF aware
  cmd/bio-rd/main.go
  examples/bgp/main.go
  net/tcp/listen.go
  net/tcp/listener_manager.go
  net/tcp/ports.go
  net/tcp/tcp.go
  protocols/bgp/api/bgp.pb.go
  protocols/bgp/api/bgp.proto
  protocols/bgp/server/bgp_api.go
  protocols/bgp/server/bgp_api_test.go
  protocols/bgp/server/fsm.go
  protocols/bgp/server/metrics_service_test.go
  protocols/bgp/server/peer.go
  protocols/bgp/server/peer_manager.go
  protocols/bgp/server/peer_manager_test.go
  protocols/bgp/server/server.go
  protocols/bgp/server/tcplistener.go
  routingtable/vrf/vrf_registry.go
Labels: type:feature

#403 Allow setting default Local Preference for eBGP sessions and default it to 100.
  cmd/bio-rd/main.go
  examples/bgp/main.go
  protocols/bgp/server/fsm_address_family.go
  protocols/bgp/server/metrics_service_test.go
  protocols/bgp/server/server.go
  routingtable/adjRIBIn/adj_rib_in.go
  routingtable/session_attrs.go
Labels: type:improvement

#410 Generalize set next-hop filter action to work for all protocols
  route/bgp_path.go
  route/path.go
  route/path_test.go
  route/static.go
  routingtable/filter/actions/set_nexthop_action.go
  routingtable/filter/actions/set_nexthop_action_test.go
Labels: type:improvement, type:feature-prep

#338 ISIS: Generate local LSPDUs
  net/ip.go
  protocols/isis/server/lsp.go
  protocols/isis/server/net_ifa_manager.go
  protocols/isis/server/server.go
Labels: type:feature

#418 ISIS: Extend integration testing
  cmd/bio-rd/is-is.go
  go.mod
  go.sum
  protocols/device/server_mock.go
  protocols/isis/server/hello_sender.go
  protocols/isis/server/isis_api.go
  protocols/isis/server/lsdb.go
  protocols/isis/server/lsp.go
  protocols/isis/server/neighbor.go
  protocols/isis/server/net_ifa.go
  protocols/isis/server/net_ifa_manager.go
  protocols/isis/server/server.go
  tests/isis_integration_test.go
  util/time/ticker.go
Labels: type:feature-prep

#420 ISIS: LSP: Add extened IS + IP reachability TLVs
  net/ethernet/ethernet_mock.go
  protocols/isis/packet/hello_test.go
  protocols/isis/packet/tlv_ip_interface_addresses.go
  protocols/isis/packet/tlv_ip_interface_addresses_test.go
  protocols/isis/server/hello_sender.go
  protocols/isis/server/lsp.go
  protocols/isis/server/neighbor.go
  protocols/isis/server/net_ifa_manager.go
  tests/isis_integration_test.go
Labels: type:feature-prep
